### ISSUE TITLE
tabris initi crashes on description when using typescript template

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js-cli#24]
Confirming every question with the default crashes the wizard when coming to the description.

```shell
? App description 
exec: internal error
(node:18232) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'stdout' of null


events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'stdout' of null
    at Object.user.git.name (C:\Users\mpost\git\tabris-js-cli\node_modules\yeoman-generator\lib\actions\user.js:30:68)
    at C:\Users\mpost\git\tabris-js-cli\node_modules\run-async\index.js:25:25
    at C:\Users\mpost\git\tabris-js-cli\node_modules\run-async\index.js:24:19
    at exports.fetchAsyncQuestionProperty (C:\Users\mpost\git\tabris-js-cli\node_modules\inquirer\lib\utils\utils.js:20:60)
    at tryCatcher (C:\Users\mpost\git\tabris-js-cli\node_modules\rx\dist\rx.js:63:31)
    at InnerObserver.Rx.FlatMapObservable.InnerObserver.next (C:\Users\mpost\git\tabris-js-cli\node_modules\rx\dist\rx.js:2140:43)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\mpost\git\tabris-js-cli\node_modules\rx\dist\rx.js:1762:31)
    at InnerObserver.tryCatcher (C:\Users\mpost\git\tabris-js-cli\node_modules\rx\dist\rx.js:63:31)
    at AutoDetachObserverPrototype.next (C:\Users\mpost\git\tabris-js-cli\node_modules\rx\dist\rx.js:5883:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\mpost\git\tabris-js-cli\node_modules\rx\dist\rx.js:1762:31)
```

**Comment by mpost** [comment]
Seen on windows using gitbash. It works as expected when using windows cmd.

**Comment by cpetrov** [comment]
It seems `exec` throws an internal error when called with parameters `git config --get user.name`, `{silent: true}` (https://github.com/yeoman/generator/blob/master/lib/actions/user.js#L30). Not sure what's the problem. Can you try updating `node` on your machine?

**Comment by mpost** [comment]
Updating from node 6 to node 8 on windows has let me go past the description check but restulted in a problem with `fs`.

```bash
mpost@MP-Dell MINGW64 ~/git/tmp                                                                                                                                                       
$ tabris init                                                                                                                                                                         
? Your project name tmp                                                                                                                                                               
? Initial version 0.1.0                                                                                                                                                               
? Type of project 2 - TypeScript App                                                                                                                                                  
? App ID example.tmp                                                                                                                                                                  
? App name Tmp                                                                                                                                                                        
? App description Example Tabris.js App                                                                                                                                               
? Author Moritz Post                                                                                                                                                                  
? Email mpost@eclipsesource.com                                                                                                                                                       
? Configure for IDE 1 - None                                                                                                                                                          
   create package.json                                                                                                                                                                
   create cordova\config.xml                                                                                                                                                          
   create .gitignore                                                                                                                                                                  
   create src\app.ts                                                                                                                                                                  
   create tsconfig.json                                                                                                                                                               
   create tslint.json                                                                                                                                                                 
npm ERR! Windows_NT 10.0.15063                                                                                                                                                        
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mpost\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "tabris@2.0.0-rc2" "--save" "--cache-min" 
"86400"                                                                                                                                                                               
npm ERR! node v8.1.4                                                                                                                                                                  
npm ERR! npm  v3.5.3                                                                                                                                                                  
npm ERR! code MODULE_NOT_FOUND                                                                                                                                                        
                                                                                                                                                                                      
npm ERR! Cannot find module 'internal/fs'                                                                                                                                             
npm ERR!                                                                                                                                                                              
npm ERR! If you need help, you may report this error at:                                                                                                                              
npm ERR!     <https://github.com/npm/npm/issues>                                                                                                                                      
                                                                                                                                                                                      
npm ERR! Please include the following file with any support request:                                                                                                                  
npm ERR!     C:\Users\mpost\git\tmp\npm-debug.log                                                                                                                                     
npm ERR! Windows_NT 10.0.15063                                                                                                                                                        
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mpost\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "typescript" "tslint" "npm-run-all" "--sav
e-dev" "--cache-min" "86400"                                                                                                                                                          
npm ERR! node v8.1.4                                                                                                                                                                  
npm ERR! npm  v3.5.3                                                                                                                                                                  
npm ERR! code MODULE_NOT_FOUND                                                                                                                                                        
                                                                                                                                                                                      
npm ERR! Cannot find module 'internal/fs'                                                                                                                                             
npm ERR!                                                                                                                                                                              
npm ERR! If you need help, you may report this error at:                                                                                                                              
npm ERR!     <https://github.com/npm/npm/issues>                                                                                                                                      
                                                                                                                                                                                      
npm ERR! Please include the following file with any support request:                                                                                                                  
npm ERR!     C:\Users\mpost\git\tmp\npm-debug.log                                                                                                                                     
```

**Comment by cpetrov** [comment]
@mpost Try to update your npm CLI: https://github.com/npm/npm/issues/14232

**Comment by mpost** [comment]
Thanks for the hint in fact. i had to remove my globally installed npm because it couldn't self update anymore. With the latest version `tabris init` works as expected on gitbash.
