### ISSUE TITLE
Most tests fail on Windows

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js-cli#41]
Running the unit tests on windows (tested two different machines) they almost all fail with not very useful error messages, often timeouts.

Example: 

```
 run
    √ fails with invalid platform argument (516ms)
    1) succeeds with platform 'android'


  7 passing (2s)
  1 failing

  1) run succeeds with platform 'android':

      expected 'Error: Failed to replace env in config: ${APPDATA}\n    at C:\\Program Files\\nodejs\\node_modules\\npm\\lib\\config\\core.js:415:13\n    at String.replace (<anonymous>)\n    at envReplace (C:\\Program Files\\nodejs\\node_modules\\npm\\lib\\config\\core.js:411:12)\n    at parseField (C:\\Program Files\\nodejs\\node_modules\\npm\\lib\\config\\core.js:389:7)\n    at C:\\Program Files\\nodejs\\node_modules\\npm\\lib\\config\\core.js:330:24\n    at Array.forEach (<anonymous>)\n    at Conf.add (C:\\Program Files\\nodejs\\node_modules\\npm\\lib\\config\\core.js:328:23)\n    at ConfigChain.addString (C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\config-chain\\index.js:244:8)\n    at Conf.<anonymous> (C:\\Program Files\\nodejs\\node_modules\\npm\\lib\\config\\core.js:316:10)\n    at C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\graceful-fs\\graceful-fs.js:78:16\nTypeError: Cannot read property \'get\' of undefined\n    at errorHandler (C:\\Program Files\\nodejs\\node_modules\\npm\\lib\\utils\\error-handler.js:205:18)\n    at C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js:76:20\n    at cb (C:\\Program Files\\nodejs\\node_modules\\npm\\lib\\npm.js:228:22)\n    at C:\\Program Files\\nodejs\\node_modules\\npm\\lib\\npm.js:266:24\n    at C:\\Program Files\\nodejs\\node_modules\\npm\\lib\\config\\core.js:83:7\n    at Array.forEach (<anonymous>)\n    at Conf.<anonymous> (C:\\Program Files\\nodejs\\node_modules\\npm\\lib\\config\\core.js:82:13)\n    at Conf.f (C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\once\\once.js:25:25)\n    at Conf.emit (events.js:182:13)\n    at Conf.add (C:\\Program Files\\nodejs\\node_modules\\npm\\lib\\config\\core.js:335:10)\nC:\\Program Files\\nodejs\\node_modules\\npm\\lib\\utils\\error-handler.js:205\r\n  if (npm.config.get(\'json\')) {\r\n                 ^\r\n\r\nTypeError: Cannot read property \'get\' of undefined\r\n    at process.errorHandler (C:\\Program Files\\nodejs\\node_modules\\npm\\lib\\utils\\error-handler.js:205:18)\r\n    at process.emit (events.js:182:13)\r\n    at process._fatalException (internal/bootstrap/node.js:441:27)\r\nError: Failed to replace env in config: ${APPDATA}\n    at C:\\Program Files\\nodejs\\node_modules\\npm\\lib\\config\\core.js:415:13\n    at String.replace (<anonymous>)\n    at envReplace (C:\\Program Files\\nodejs\\node_modules\\npm\\lib\\config\\core.js:411:12)\n    at parseField (C:\\Program Files\\nodejs\\node_modules\\npm\\lib\\config\\core.js:389:7)\n    at C:\\Program Files\\nodejs\\node_modules\\npm\\lib\\config\\core.js:330:24\n    at Array.forEach (<anonymous>)\n    at Conf.add (C:\\Program Files\\nodejs\\node_modules\\npm\\lib\\config\\core.js:328:23)\n    at ConfigChain.addString (C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\config-chain\\index.js:244:8)\n    at Conf.<anonymous> (C:\\Program Files\\nodejs\\node_modules\\npm\\lib\\config\\core.js:316:10)\n    at C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\graceful-fs\\graceful-fs.js:78:16\nTypeError: Cannot read property \'get\' of undefined\n    at errorHandler (C:\\Program Files\\nodejs\\node_modules\\npm\\lib\\utils\\error-handler.js:205:18)\n    at C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js:76:20\n    at cb (C:\\Program Files\\nodejs\\node_modules\\npm\\lib\\npm.js:228:22)\n    at C:\\Program Files\\nodejs\\node_modules\\npm\\lib\\npm.js:266:24\n    at C:\\Program Files\\nodejs\\node_modules\\npm\\lib\\config\\core.js:83:7\n    at Array.forEach (<anonymous>)\n    at Conf.<anonymous> (C:\\Program Files\\nodejs\\node_modules\\npm\\lib\\config\\core.js:82:13)\n    at Conf.f (C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\once\\once.js:25:25)\n    at Conf.emit (events.js:182:13)\n    at Conf.add (C:\\Program Files\\nodejs\\node_modules\\npm\\lib\\config\\core.js:335:10)\nC:\\Program Files\\nodejs\\node_modules\\npm\\lib\\utils\\error-handler.js:205\r\n  if (npm.config.get(\'json\')) {\r\n                 ^\r\n\r\nTypeError: Cannot read property \'get\' of undefined\r\n    at process.errorHandler (C:\\Program Files\\nodejs\\node_modules\\npm\\lib\\utils\\error-handler.js:205:18)\r\n    at process.emit (events.js:182:13)\r\n    at process._fatalException (internal/bootstrap/node.js:441:27)\r\nThe command npm exited with 7\n' to equal ''
      + expected - actual

      -Error: Failed to replace env in config: ${APPDATA}
      -    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:415:13
      -    at String.replace (<anonymous>)
      -    at envReplace (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:411:12)
      -    at parseField (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:389:7)
      -    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:330:24
      -    at Array.forEach (<anonymous>)
      -    at Conf.add (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:328:23)
      -    at ConfigChain.addString (C:\Program Files\nodejs\node_modules\npm\node_modules\config-chain\index.js:244:8)
      -    at Conf.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:316:10)
      -    at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
      -TypeError: Cannot read property 'get' of undefined
      -    at errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205:18)
      -    at C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:76:20
      -    at cb (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:228:22)
      -    at C:\Program Files\nodejs\node_modules\npm\lib\npm.js:266:24
      -    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:83:7
      -    at Array.forEach (<anonymous>)
      -    at Conf.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:82:13)
      -    at Conf.f (C:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:25:25)
      -    at Conf.emit (events.js:182:13)
      -    at Conf.add (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:335:10)
      -C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205
      -  if (npm.config.get('json')) {
      -                 ^
      -
      -TypeError: Cannot read property 'get' of undefined
      -    at process.errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205:18)
      -    at process.emit (events.js:182:13)
      -    at process._fatalException (internal/bootstrap/node.js:441:27)
      -Error: Failed to replace env in config: ${APPDATA}
      -    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:415:13
      -    at String.replace (<anonymous>)
      -    at envReplace (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:411:12)
      -    at parseField (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:389:7)
      -    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:330:24
      -    at Array.forEach (<anonymous>)
      -    at Conf.add (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:328:23)
      -    at ConfigChain.addString (C:\Program Files\nodejs\node_modules\npm\node_modules\config-chain\index.js:244:8)
      -    at Conf.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:316:10)
      -    at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
      -TypeError: Cannot read property 'get' of undefined
      -    at errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205:18)
      -    at C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:76:20
      -    at cb (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:228:22)
      -    at C:\Program Files\nodejs\node_modules\npm\lib\npm.js:266:24
      -    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:83:7
      -    at Array.forEach (<anonymous>)
      -    at Conf.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:82:13)
      -    at Conf.f (C:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:25:25)
      -    at Conf.emit (events.js:182:13)
      -    at Conf.add (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:335:10)
      -C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205
      -  if (npm.config.get('json')) {
      -                 ^
      -
      -TypeError: Cannot read property 'get' of undefined
      -    at process.errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205:18)
      -    at process.emit (events.js:182:13)
      -    at process._fatalException (internal/bootstrap/node.js:441:27)
      -The command npm exited with 7

      at Context.<anonymous> (test\build.test.js:57:34)
```

**Comment by tbuschto** [comment]
resolved a while ago
