### ISSUE TITLE
MacOS Serve Fails

### ISSUE THREAD

**Issue by raphaelpreston** [eclipsesource/tabris-js-cli#59]
### Problem description
Unable to serve, fails on `TypeError: networkUtils.qualityFromDB is not a function`.

### Environment

- Tabris.js version: nightly (3.0.0-beta2-dev.20190228)
- OS: macOS Sierra 10.12.6

### Console Output

```
News-MacBook-Pro:Documents developer$ git clone https://github.com/raphaelpreston/TabrisExample.git
Cloning into 'TabrisExample'...
remote: Enumerating objects: 23, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 23 (delta 5), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (23/23), done.
News-MacBook-Pro:Documents developer$ cd TabrisExample/
News-MacBook-Pro:TabrisExample developer$ ls
cordova		package.json	src
News-MacBook-Pro:TabrisExample developer$ npm install
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm notice created a lockfile as package-lock.json. You should commit this file.
added 131 packages from 139 contributors and audited 203 packages in 4.901s
found 0 vulnerabilities

News-MacBook-Pro:TabrisExample developer$ tabris --version
3.0.0-beta2-dev.20190227
News-MacBook-Pro:TabrisExample developer$ tabris serve
[/Users/developer/Documents/TabrisExample] npm run --if-present build
/usr/local/lib/node_modules/tabris-cli/node_modules/node-wifi/src/mac-current-connections.js:14
            connection.quality = networkUtils.qualityFromDB(parseInt(line.match(/[ ]*agrCtlRSSI: (.*)/)[1]));
                                              ^

TypeError: networkUtils.qualityFromDB is not a function
    at /usr/local/lib/node_modules/tabris-cli/node_modules/node-wifi/src/mac-current-connections.js:14:47
    at Array.forEach (<anonymous>)
    at parseAirport (/usr/local/lib/node_modules/tabris-cli/node_modules/node-wifi/src/mac-current-connections.js:11:11)
    at /usr/local/lib/node_modules/tabris-cli/node_modules/node-wifi/src/mac-current-connections.js:42:40
    at ChildProcess.exithandler (child_process.js:285:7)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:610:12)
```

-----
### Workaround
Credit to @cookieguru. See workaround [here](https://github.com/eclipsesource/tabris-js/issues/1803).

**Comment by tbuschto** [comment]
Is this still an issue in the 3.0 beta2?

**Comment by raphaelpreston** [comment]
Yes, I updated the dependency for my [example project](https://github.com/raphaelpreston/TabrisExample) to `3.0.0-beta2` and installed the CLI at 3.0.0-beta2. Here is the output of me repeating the same process in the original post:
```
News-MacBook-Pro:testtest developer$ git clone https://github.com/raphaelpreston/TabrisExample.git
Cloning into 'TabrisExample'...
remote: Enumerating objects: 26, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 26 (delta 7), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (26/26), done.

News-MacBook-Pro:testtest developer$ cd TabrisExample/
News-MacBook-Pro:TabrisExample developer$ npm i
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm notice created a lockfile as package-lock.json. You should commit this file.
added 131 packages from 139 contributors and audited 203 packages in 3.664s
found 0 vulnerabilities

News-MacBook-Pro:TabrisExample developer$ tabris --version
3.0.0-beta2

News-MacBook-Pro:TabrisExample developer$ ls
cordova			node_modules		package-lock.json	package.json		src

News-MacBook-Pro:TabrisExample developer$ tabris serve
[/Users/developer/Documents/testtest/testtest/TabrisExample] npm run --if-present build
/usr/local/lib/node_modules/tabris-cli/node_modules/node-wifi/src/mac-current-connections.js:14
            connection.quality = networkUtils.qualityFromDB(parseInt(line.match(/[ ]*agrCtlRSSI: (.*)/)[1]));
                                              ^
TypeError: networkUtils.qualityFromDB is not a function
    at /usr/local/lib/node_modules/tabris-cli/node_modules/node-wifi/src/mac-current-connections.js:14:47
    at Array.forEach (<anonymous>)
    at parseAirport (/usr/local/lib/node_modules/tabris-cli/node_modules/node-wifi/src/mac-current-connections.js:11:11)
    at /usr/local/lib/node_modules/tabris-cli/node_modules/node-wifi/src/mac-current-connections.js:42:40
    at ChildProcess.exithandler (child_process.js:285:7)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:610:12)
```

**Comment by cookieguru** [comment]
I've opened #60 to gracefully handle the errors in the third-party library

**Comment by cpetrov** [comment]
Issue https://github.com/friedrith/node-wifi/issues/57 had been fixed: https://github.com/friedrith/node-wifi/issues/57 but the fix is not released yet. This issue is a regression not present in the previous version of the library: https://github.com/friedrith/node-wifi/issues/65#issuecomment-468299258. The error is thrown before the promise from https://github.com/friedrith/node-wifi/blob/master/src/mac-current-connections.js#L52 resolves, so unfortunately there is no way to handle this particular issue in Tabris CLI.

This problem will currently occur when running `tabris serve` on a Mac with more than one external addresses.

We have discovered another issue in our usage of `node-wifi`. On Mac, connections returned by `getCurrentConnections()` don't have the `iface` field which we use to match the `os.networkConnections()` output: https://github.com/eclipsesource/tabris-js-cli/blob/master/src/services/ServerInfo.js#L52. We may want to look into using e.g. `networksetup -listallhardwareports` instead on Mac to determine which network interfaces are wireless.

For now, we will not use `node-wifi` on Mac and instead generate the QR code always based on the first external address returned by `os.networkConnections()`.
